[package]
name = "ameath-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29.15", features = ["rwh_05"] }
softbuffer = "0.4.1"
raw-window-handle = "0.5.2"
image = "0.24"
rand = "0.8"
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
] }
rusttype = "0.9.3"
rodio = "0.19"
rfd = "0.15"
